Google Refresh Token

diff --git a/scripts/jira-app-token b/scripts/jira-app-token
--- a/scripts/jira-app-token
+++ b/scripts/jira-app-token
@@ -3,17 +3,22 @@ set -eu
 set -o pipefail
 #
 
-usage="Usage: $(basename $0) [-h]
+usage="Usage: $(basename $0) [-h][-c]
     -h - help
+    -c - check
 
 Prints a short lived access token for jira-app
 "
 
+check="no"
 while [ $# -gt 0 ]; do
     case "$1" in
         -h|-\?)
             echo "$usage"
             exit 0
+        ;;
+        -c)
+            check="yes"
         ;;
         *)
             break
@@ -22,24 +27,18 @@ while [ $# -gt 0 ]; do
     shift
 done
 
-if [ -z "${APP_TOKEN_URI:-}" ]; then
-    APP_TOKEN_URI=$(find $AI_HOME/jira-app/build -name application.properties | xargs grep app.token_uri | awk -F= '{print $2}')
-    if [ -z "$APP_TOKEN_URI" ]; then
-        echo "Error: unable to find app app_token_uri" 1>&2
-        exit 1
-    fi
+if [ -z "${GOOGLE_TOKEN_URI:-}" ]; then
+    echo "Error: GOOGLE_TOKEN_URI not defined" 1>&2
+    exit 1
 fi
 
-if [ -z "${APP_CLIENT_ID:-}" ]; then
-    APP_CLIENT_ID=$(find $AI_HOME/jira-app/build -name application.properties | xargs grep app.client_id | awk -F= '{print $2}')
-    if [ -z "$APP_CLIENT_ID" ]; then
-        echo "Error: unable to find app client_id" 1>&2
-        exit 1
-    fi
+if [ -z "${GOOGLE_CLIENT_ID:-}" ]; then
+    echo "Error: GOOGLE_CLIENT_ID not defined" 1>&2
+    exit 1
 fi
 
-if [ -z "$APP_CLIENT_SECRET" ]; then
-    echo "Error: APP_CLIENT_SECRET not defined" 1>&2
+if [ -z "$GOOGLE_CLIENT_SECRET" ]; then
+    echo "Error: GOOGLE_CLIENT_SECRET not defined" 1>&2
     exit 1
 fi
 
@@ -48,13 +47,13 @@ if [ -z "$APP_REFRESH_TOKEN" ]; then
     exit 1
 fi
 
-TOKEN_RESPONSE=$(curl -s -X POST $APP_TOKEN_URI \
-  -d client_id=$APP_CLIENT_ID \
-  -d client_secret=$APP_CLIENT_SECRET \
+TOKEN_RESPONSE=$(curl -s -X POST $GOOGLE_TOKEN_URI \
+  -d client_id=$GOOGLE_CLIENT_ID \
+  -d client_secret=$GOOGLE_CLIENT_SECRET \
   -d refresh_token=$APP_REFRESH_TOKEN \
   -d grant_type=refresh_token)
 
-ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.access_token')
+ACCESS_TOKEN=$(echo $TOKEN_RESPONSE | jq -r '.id_token')
 
 if [[ "$ACCESS_TOKEN" == "null" || -z "$ACCESS_TOKEN" ]]; then
   echo "Error: Failed to retrieve access token" 1>&2
@@ -62,4 +61,9 @@ if [[ "$ACCESS_TOKEN" == "null" || -z "$ACCESS_TOKEN" ]]; then
 fi
 
 echo "$ACCESS_TOKEN"
+
+if [ "$check" == "yes" ]; then
+  echo 
+  curl -H "Authorization: Bearer $ACCESS_TOKEN" 'https://www.googleapis.com/oauth2/v3/tokeninfo'
+fi
 
